### ISSUE TITLE
Ability to clone collector configuration

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog-plugin-collector#10]
### Problem description
I'd like to request a mechanism to clone a collector configuration (outputs, inputs, and snippets; potentially excluding tags to avoid Sidecar detection).

We define configurations on a per team, environment, and server type basis.  Within a team's "server type" there are only a few minor differences... most notably each environment's unique Graylog input `port`.  It would save time to be able to clone an existing collector configuration and make the 1-2 required changes.

### Environment
* Graylog Version: 2.0.3
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 47

**Comment by tehpanta** [comment]
This would be hugely beneficial in our environment as well! +1

**Comment by mariussturm** [comment]
This will be in 2.1.0-RC1 https://github.com/Graylog2/graylog-plugin-collector/commit/814e039042914d387d6d6c5b363f4b4c388693cc
