### ISSUE TITLE
Sidecar nxlog input/output view

### ISSUE THREAD

**Issue by Linwood-F** [Graylog2/graylog-plugin-collector#12]
I've found two issues in Beta 1 of 2.1 (I have not put beta 2 in so apologies if this was already addressed but didn't see it).  One I think is a bug, one is... an inconvenient feature perhaps.

The first I'd call a bug is that the text entered in the "arbitrary text" is inserted without a new line following it.  Consider the "input" section.  If you put a line of code, without adding an empty line, the resulting code in the config file is: 

`        Exec If $SourceName == 'Microsoft-Windows-StorDiag' drop();</Input>`

The trailing close of the input tag is the a syntax error.  I can't think of any circumstance where you want code with the closing tag appended before line end, so you will cut down on a lot of (fairly hidden) errors if you ensure the arbitrary text ends in a new line.

The other issue is that the section is hidden (initially collapsed).  I get that you did that to reduce casual use and mistakes, but once it has content, it should always be shown expanded.  Otherwise if you go into the dialog, it is very easy to get confused and think there is no text there.   I would suggest that if you want it initially collapsed, only do so when it is empty.

Thanks,
Linwood

**Comment by mariussturm** [comment]
Thanks for testing the beta and providing feedback. Both issues are fixed now and will be included in the next beta! https://github.com/Graylog2/graylog-plugin-collector/commit/363cab63b6ec51747e0d81268f24fa5920eefc04

**Comment by Linwood-F** [comment]
Now that's fast turnaround.  Thanks.
