### ISSUE TITLE
Wrong URL in the submenu

### ISSUE THREAD

**Issue by tomasnk** [Graylog2/graylog-plugin-collector#122]
Hi

When we run graylog with the URL 127.0.0.1:9000/graylog the submenu "Collectors" is linked to 127.0.0.1:9000/system/collectors instead of 127.0.0.1:9000/graylog/system/collectors .

We can access to the page by manually browsing to 127.0.0.1:9000/graylog/system/collectors

Thanks

**Comment by mariussturm** [comment]
Hi @tomasnk,
can you please give us some insights how you configured the subdomain exactly? Is this done via a web server infront of Graylog? How does the configuration looks like?

Thanks,
Marius

**Comment by tomasnk** [comment]
Hi,
In the configuration files I have configure:
http_publish_uri = http://127.0.0.1:9000/graylog

Thanks
Thomas

**Comment by mariussturm** [comment]
Not only the Collector plugin is affected by this, also all other plugins so I have created an issue in the server repository. Please follow https://github.com/Graylog2/graylog2-server/issues/6149 for updates!
