### ISSUE TITLE
Beats TLS Output Configuration Creating Unnecessary Winlog Config

### ISSUE THREAD

**Issue by Fossiltalk** [Graylog2/graylog-plugin-collector#30]
Checking "Enable TLS Support" in the Winlogbeat Output causes it to force the following in the TLS section of the winlogbeat.yml auto-configuration:
certificate_authorities:
      - ""

This causes winlogbeat to fail to execute.  The same configuration in Filebeat Output does not cause the bad certificate_authorities field to appear, and that configuration is functional.

**Comment by mariussturm** [comment]
@Fossiltalk which sidecar version do you use? This should already be fixed in 0.1.0-alpha.2

**Comment by Fossiltalk** [comment]
I'm on the latest stable, which I believe is 0.0.9, and I am using the 64-bit client for Windows.

**Comment by mariussturm** [comment]
Ok thanks. Should then be fixed when 0.1.0 is out. Closing this for now, feel free to add comments when the probelm still exist afterwards.

**Comment by Fossiltalk** [comment]
I'm on the latest stable, which I believe is 0.0.9, and I am using the
64-bit client for Windows.



I did notice another issue, but I'm not sure if it's a filebeat issue or if
it's a Layer 8 issue:

I'm trying to read in MSSQL logs, which are UTF-16 LE encoded.  I know I
have to modify the filebeat configuration to accommodate this, but whenever
I try adding *encoding:utf-16le* as a beats snippet, it does not appear to
change filebeat's behavior.

In graylog, this results in an inability to write extractors for the log
messages.  I believe this is because the messages are being read as UTF-8,
meaning that UTF-8 character is being read, followed by a null character
for each UTF-16 character.  This becomes more evident when you show terms
on a log message:

[image: Inline image 1]

To get around this an extractor has to be written to re-write the message
body without each of those null characters, or to accommodate them in-line,
which is rather expensive.

Best Regards,
Aaron M Simmons

**Comment by mariussturm** [comment]
Please dont mix issues, when there is a another problem feel free to open a new ticket for it. General questions which are no bug reports should go to our mailing list or irc channel. And also take a look into the official Filebeat documention: https://www.elastic.co/guide/en/beats/filebeat/1.3/configuration-filebeat-options.html

**Comment by Fossiltalk** [comment]
Sorry, I opened another case.  Didn't realize email responses got pushed into comments.
