### ISSUE TITLE
System/Collectors not available

### ISSUE THREAD

**Issue by gauravarora** [Graylog2/graylog-plugin-collector#48]
I'm running Graylog v2.2.2 inside a docker container. I have two plugins running, beats input and collector. Both plugins show up on the configuration page.

I have a sidecar running on the physical host. However the option to configure collector sidecar presumably under http://ip:9000/system/collectors does not exist. Is this a configuration mistake somewhere? Do I need to enable this plugin with additional options?

**Comment by joschi** [comment]
@gauravarora The Collector plugin is being shipped with Graylog.

* Which Docker image are you using?
* Does the Collector plugin show up in the logs of your Graylog container on startup?

**Comment by gauravarora** [comment]
@joschi I'm using version 2.2.2-1 from https://hub.docker.com/r/graylog2/server/

I have the plugin jar, graylog-plugin-collector-2.2.2.jar in the plugin folder of graylog also. The plugin does show as loaded in the logs.
```
2017-03-06 13:34:50,492 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Collector 2.2.2 [org.graylog.plugins.collector.CollectorPlugin]
```
If I remove the plugin jar then the log line does not show up.

**Comment by joschi** [comment]
@gauravarora I guess you're shadowing the plugin directory of the Graylog Docker image.

If you're only using plugins which are shipped with Graylog anyway (Beats, Collector, Processing Pipelines), then you don't need to do this.

If you're using some 3rd party plugins which are not shipped with Graylog, you need to put **all** plugins into the plugin directory you want to use.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
