### ISSUE TITLE
nxlog: Explicitly set ShortMessageLength

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-collector#6]
The nxlog GELF output by default cuts off messages (`short_message`) at 64 characters which might be unintuitive to most users.

The `ShortMessageLength` setting for nxlog should explicitly be set to a higher (or configurable value) to avoid incomplete messages.

From https://nxlog.co/docs/nxlog-ce/nxlog-reference-manual.html#xm_gelf
> `ShortMessageLength`
This optional directive can be used to specify the length of the short_message field. This defaults to 64 if the directive is not explicitly specified. If the field short_message or ShortMessage is present, it will not be truncated.

https://nxlog.co/question/1037/short-messages-truncated-64-chars

**Comment by renapu** [comment]
Please let it also be a negative value. We are using -1 in all configs.

**Comment by mariussturm** [comment]
We avoid truncation of the short_message field by setting it to $raw_event now.
