### ISSUE TITLE
Versioned configurations

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-collector#67]
It would be great to have versioned configurations that you can roll back to in case you made an error in a new configuration. It would also make debugging easier by seeing when a change happened and what change that was.

The sidecar makes changing settings so easy (that's its goal!) that we need to make making accidental or erroneous changes as hard as possible.

**Comment by bernd** [comment]
This can be done with the new sidecar code in 3.0.
