### ISSUE TITLE
Support new collectors

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-collector#70]
- [ ] Topbeat (meh, but quite a lot of customers asked for it)
- [ ] Auditbeat (crucial for many security use-cases)
- [ ] Packetbeat (crucial for many security use-cases)

**Comment by bernd** [comment]
Will be possible in Graylog 3.0.

**Comment by rdemendoza** [comment]
Any update on theses ?

**Comment by bernd** [comment]
@rdemendoza Graylog 3.0 allows you to run arbitrary log collectors via the sidecar.

See our documentation: http://docs.graylog.org/en/3.0/pages/sidecar.html#step-by-step-guide
