### ISSUE TITLE
Move collector logic to graylog-server

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-collector#71]
Currently, to support a new collector, logic has to be added in the `graylog-server` plugin and the `collector-sidecar` binary. 

This obviously adds complexity in development and version compatibility (including enforced upgrades on all your machines that run the sidecar) but also requires golang knowledge.

Is there a way we could make the `collector-sidecar` dumber and the `graylog-server` plugin do more? Maybe we could have the `collector-sidecar` purely manage configuration files and processes but nothing else, while the `graylog-server` plugin ships complete configuration files?

Issues #69, #70 might be very much related to this.

**Comment by edmundoa** [comment]
This is done now.
