### ISSUE TITLE
Plugin availability as a jar?

### ISSUE THREAD

**Issue by rochbu** [Graylog2/graylog-plugin-collector#8]
The plugin appears to be available source only.
The instructions imply availability as a jar (pre-built) for deploy.
Is the plugin available as a pre-built jar?
Thanks,

Rob

**Comment by cloudlady911** [comment]
Same question here.  There is no jar file in the zip.

**Comment by cloudlady911** [comment]
I found a .jar file here: https://fossies.org/linux/misc/graylog-2.0.2.tgz/graylog-2.0.2/plugin/graylog-plugin-collector-1.0.2.jar

**Comment by rochbu** [comment]
Determined the plugin is distributed with graylog server. The error message I was chasing wasn't reflective of the plugin not being there but that an output had to be defined first. So from my perspective I no longer require resolution.

Having said that it does seem the release output should be the jars etc (build target) and not the build source.
