### ISSUE TITLE
Display collector IP address

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog-plugin-collector#9]
### Problem description
As an admin of Graylog environments where installation and configuration of the Sidecar is delegated to various teams, I would like the ability to view a collector's IP address alongside the other collector status information.  This would be useful in cases where a collector may not have an accurate name (e.g. "localhost") and/or I need to assist with troubleshooting an issue.

I have set up a logger for `org.graylog2.rest.accesslog`, so I can dig in to get an IP if absolutely needed, but it would be much more convenient to have that info displayed with the other collector info.

### Environment
* Graylog Version: 2.0.3
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 47

**Comment by mariussturm** [comment]
This will be in Graylog 2.1.0-RC1 and Sidecar 0.0.9-RC1 https://github.com/Graylog2/graylog-plugin-collector/commit/6716b05fba874c8c211c46c74fd0d394475158ef

**Comment by coffee-squirrel** [comment]
Greatly appreciated!

**Comment by mariussturm** [comment]
Forgot to mention: you have to set `send_status: true` in the Sidecar config then you can find the IP on the collector status page.
