### ISSUE TITLE
Mark old collector plugin as deprecated

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog-plugin-collector#90]
This plugin can be used in 3.0 to help with the migration to the new sidecar implementation. To make it clear that it is deprecated, we should adjust the UI.

- Change system menu entry from "Collectors" to "Collectors (legacy)" or "Collectors (deprecated)"
- Add a deprecation notification to all legacy collector pages

**Comment by edmundoa** [comment]
The first point in the list was already done in https://github.com/Graylog2/graylog-plugin-collector/commit/90f0a6f57b1f9dee9e0620345c0b4e90e0a8dbed
